#################################
######## Import Packages #######
#################################

import pandas as pd
import numpy as np

## Data Set Loading.
df = pd.read_excel("Case Study - VC funding data.xlsx",sheet_name="Funding Data")

# Knowing Variables.
df.info()

# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 1460 entries, 0 to 1459
# Data columns (total 9 columns):
# permalink         1456 non-null object
# company           1460 non-null object
# Employee count    567 non-null float64
# category          1436 non-null object
# city              1423 non-null object
# fundedDate        1460 non-null int64
# raisedAmt         1460 non-null float64
# raisedCurrency    1460 non-null object
# round             1460 non-null object
# dtypes: float64(2), int64(1), object(6)
# memory usage: 102.7+ KB

# Seems Permalink Link is less important since it gives a information only about particular blog post
# Dropping permalink

df.drop(["permalink"],axis=1,inplace=True)

# Checking "NA" Values.
pd.isna(df).sum()

					# NA Values
# company             0
# Employee count    893
# category           24
# city               37
# fundedDate          0
# raisedAmt           0
# raisedCurrency      0
# round               0

#########################
#### Data Cleaning ######
#########################

### Company Variable
df.company.str.strip()
company=pd.pivot_table(data=df,index="company",aggfunc="count",margins=True)
company.to_excel("Company.xlsx",sheet_name="company")

# I found discrepancies in the names of companies. like junk chara and unwanted "spaces" in between. 
# Googled the names inividually and corrected 
# For correct names, i refered Wiki, crunchbase,techcrunch webs.
# Corrected spelling mistakes as well.

# Codes for correct Company names.
df.company.replace("23 andMe","23andMe",inplace=True)
df.company.replace("3Jam","3Jam",inplace=True)
df.company.replace("4HomeMe dia","4HomeMedia",inplace=True)
df.company.replace("5min","5min",inplace=True)
df.company.replace("750 In dustries","750 Industries",inplace=True)
df.company.replace("A123Sys tems","A123 Systems",inplace=True)
df.company.replace("A123Systems","A123 Systems",inplace=True)
df.company.replace("Accertify","Accertify",inplace=True)
df.company.replace("AccountNow","AccountNow",inplace=True)
df.company.replace("Acinion","Acinion",inplace=True)
df.company.replace("Acquia","Acquia",inplace=True)
df.company.replace("Act ion Engine","Action Engine",inplace=True)
df.company.replace("Action  Engine","Action Engine",inplace=True)
df.company.replace("Action Engine","Action Engine",inplace=True)
df.company.replace("Ad I nfuse","Ad Infuse",inplace=True)
df.company.replace("Ad Infuse","Ad Infuse",inplace=True)
df.company.replace("Ad Mob","Admob",inplace=True)
df.company.replace("Ad otube","Adotube",inplace=True)
df.company.replace("AdB rite","AdBrite",inplace=True)
df.company.replace("AdBr ite","AdBrite",inplace=True)
df.company.replace("AdBrite","AdBrite",inplace=True)
df.company.replace("AdReady","AdReady",inplace=True)
df.company.replace("Adap.tv","Adap.tv",inplace=True)
df.company.replace("AdaptiveBlue","AdaptiveBlue",inplace=True)
df.company.replace("Adconion Media Group","Adconion Media Group",inplace=True)
df.company.replace("Adify","Adify",inplace=True)
df.company.replace("Adotube","Adotube",inplace=True)
df.company.replace("Aductio ns","Aductio ns",inplace=True)
df.company.replace("Aeria","Aeria",inplace=True)
df.company.replace("Af finity Circles","Affinity Circles",inplace=True)
df.company.replace("Affi nity Internet","Affinity Internet",inplace=True)
df.company.replace("Affinity Circles","Affinity Circles",inplace=True)
df.company.replace("Affinity Internet","Affinity Internet",inplace=True)
df.company.replace("Aggreg ate Knowledge","Aggregate Knowledge",inplace=True)
df.company.replace("Aggregate Knowledge","Aggregate Knowledge",inplace=True)
df.company.replace("Agili s Systems","Agilis Systems",inplace=True)
df.company.replace("Aki mbo","Akimbo",inplace=True)
df.company.replace("Akimbo","Akimbo",inplace=True)
df.company.replace("Alerts.com","Alerts.com",inplace=True)
df.company.replace("Aliph","Aliph",inplace=True)
df.company.replace("All Business.com","AllBusiness.com",inplace=True)
df.company.replace("AllBusiness.com","AllBusiness.com",inplace=True)
df.company.replace("Allvoices","AllVoices",inplace=True)
df.company.replace("AmericanTowns.com","AmericanTowns.com",inplace=True)
df.company.replace("Amobee","Amobee",inplace=True)
df.company.replace("Anc estry.com","Ancestry.com",inplace=True)
df.company.replace("Anchor Intelligence","Anchor Intelligence",inplace=True)
df.company.replace("Answ ers Corporation","Answers Corporation",inplace=True)
df.company.replace("Answers Corporation","Answers Corporation",inplace=True)
df.company.replace("Anvat o","Anvato",inplace=True)
df.company.replace("Appian","Appian",inplace=True)
df.company.replace("Appir io","Appirio",inplace=True)
df.company.replace("Appirio","Appirio",inplace=True)
df.company.replace("Apprema","Apprema",inplace=True)
df.company.replace("Aria Systems","Aria Systems",inplace=True)
df.company.replace("Art.com","Art.com",inplace=True)
df.company.replace("As k.com","Ask.com",inplace=True)
df.company.replace("Assoc iated Content","Associated Content",inplace=True)
df.company.replace("Associated Content","Associated Content",inplace=True)
df.company.replace("Asta ro","Astaro",inplace=True)
df.company.replace("Astaro","Astaro",inplace=True)
df.company.replace("Aster Data Systems","Aster Data Systems",inplace=True)
df.company.replace("At tributor","Attributor",inplace=True)
df.company.replace("Atom Shockwave","Atom Shockwave",inplace=True)
df.company.replace("Attributor","Attributor",inplace=True)
df.company.replace("Aur ora Biofuels","Aurora Biofuels",inplace=True)
df.company.replace("Ausra","Ausra",inplace=True)
df.company.replace("Aut henticlick","Authenticlick",inplace=True)
df.company.replace("Automa ttic","Automattic",inplace=True)
df.company.replace("Automattic","Automattic",inplace=True)
df.company.replace("Avail M edia","Avail Media",inplace=True)
df.company.replace("Avail Media","Avail Media",inplace=True)
df.company.replace("Azuki Systems","Azuki Systems",inplace=True)
df.company.replace("B-hive  Networks","B-hive Networks",inplace=True)
df.company.replace("Ba lihoo","Balihoo",inplace=True)
df.company.replace("Balihoo","Balihoo",inplace=True)
df.company.replace("Batanga","Batanga Media",inplace=True)
df.company.replace("Bazaa rvoice","Bazaarvoice",inplace=True)
df.company.replace("Bazaar voice","Bazaarvoice",inplace=True)
df.company.replace("Bazaarvoice","Bazaarvoice",inplace=True)
df.company.replace("Be tter World Books","Better World Books",inplace=True)
df.company.replace("Bebo","Bebo",inplace=True)
df.company.replace("Become","Become.com",inplace=True)
df.company.replace("Bi lleo","Billeo",inplace=True)
df.company.replace("Bi tTorrent","BitTorrent",inplace=True)
df.company.replace("Bill Me Later","Bill Me Later",inplace=True)
df.company.replace("Billeo","Billeo",inplace=True)
df.company.replace("Bio Wizard","BioWizard",inplace=True)
df.company.replace("BitPa ss","BitPass",inplace=True)
df.company.replace("BitPass","BitPass",inplace=True)
df.company.replace("BitTorrent","BitTorrent",inplace=True)
df.company.replace("Bl owtorch","Blowtorch",inplace=True)
df.company.replace("BlackA rrow","BlackArrow",inplace=True)
df.company.replace("BlackArrow","BlackArrow",inplace=True)
df.company.replace("Blis t","Blist",inplace=True)
df.company.replace("Blog Talk Radio","BlogTalkRadio",inplace=True)
df.company.replace("BlueLithium","BlueLithium",inplace=True)
df.company.replace("Blurb","Blurb",inplace=True)
df.company.replace("Board walktech","Boardwalktech",inplace=True)
df.company.replace("Booking Angel","Booking Angel",inplace=True)
df.company.replace("Boomi ","Dell Boomi",inplace=True)
df.company.replace("Boonty","Boonty",inplace=True)
df.company.replace("Bosto n Power","Boston-Power",inplace=True)
df.company.replace("Boston Power","Boston-Power",inplace=True)
df.company.replace("Bountii","Bountii",inplace=True)
df.company.replace("BountyJobs","BountyJobs",inplace=True)
df.company.replace("Box.n et","box.net",inplace=True)
df.company.replace("Br ightkite","Brightkite",inplace=True)
df.company.replace("Bre ak","Break.com",inplace=True)
df.company.replace("BreakingPoint Systems","BreakingPoint Systems",inplace=True)
df.company.replace("Brig htcove","Brightcove",inplace=True)
df.company.replace("Bright Qube","Bright Cube",inplace=True)
df.company.replace("BrightDoor Systems","BrightDoor Systems",inplace=True)
df.company.replace("BrightRo ll","BrightRoll",inplace=True)
df.company.replace("Brightco ve","Brightcove",inplace=True)
df.company.replace("Brightcove","Brightcove",inplace=True)
df.company.replace("Brightkite","Brightkite",inplace=True)
df.company.replace("Brilli ant Telecom","Brilliant Telecom ",inplace=True)
df.company.replace("Broadband Enterprises","Broadband Enterprises",inplace=True)
df.company.replace("Bu nchball","Bunchball",inplace=True)
df.company.replace("Bu xfer","Buxfer",inplace=True)
df.company.replace("Bubble  Motion","Bubble Motion",inplace=True)
df.company.replace("Bubble Motion","Bubble Motion",inplace=True)
df.company.replace("Budd yTV","BuddyTV",inplace=True)
df.company.replace("BuddyTV","BuddyTV",inplace=True)
df.company.replace("BuddyTV ","BuddyTV",inplace=True)
df.company.replace("Bungee Labs","Bungee Labs",inplace=True)
df.company.replace("Buxfe r","Buxfer",inplace=True)
df.company.replace("Buz zNet","Buzznet",inplace=True)
df.company.replace("Buzz Net","Buzznet",inplace=True)
df.company.replace("BuzzDash","BuzzDash",inplace=True)
df.company.replace("Buzzwire","Buzzwire",inplace=True)
df.company.replace("CHI C.TV","chic.tv",inplace=True)
df.company.replace("Cafepress","CafePress",inplace=True)
df.company.replace("CarDomai n Network","CarDomain Network",inplace=True)
df.company.replace("Carb onite","Carbonite",inplace=True)
df.company.replace("Carbo nite","Carbonite",inplace=True)
df.company.replace("CarbonF low","Carbonflow",inplace=True)
df.company.replace("Carbonite","Carbonite",inplace=True)
df.company.replace("Care.com","Care.com",inplace=True)
df.company.replace("CareFlash","CareFlash",inplace=True)
df.company.replace("Caring.com","Caring.com",inplace=True)
df.company.replace("CashView","CashView",inplace=True)
df.company.replace("CastTV","CastTV",inplace=True)
df.company.replace("Causes","Causes",inplace=True)
df.company.replace("Cdigi x","Cdigix",inplace=True)
df.company.replace("CellSpin","CellSpin",inplace=True)
df.company.replace("Cen ter'd","Center'd",inplace=True)
df.company.replace("Cente r'd","Center'd",inplace=True)
df.company.replace("Center' d","Center'd",inplace=True)
df.company.replace("Central Desktop","Central Desktop",inplace=True)
df.company.replace("Ch aCha","ChaCha",inplace=True)
df.company.replace("Ch osenList.com","ChosenList.com",inplace=True)
df.company.replace("ChaCha","ChaCha",inplace=True)
df.company.replace("Challenge Games","Challenge Games",inplace=True)
df.company.replace("ChannelAdvisor","ChannelAdvisor",inplace=True)
df.company.replace("Chess Park","Chesspark",inplace=True)
df.company.replace("Cho iceStream","ChoiceStream",inplace=True)
df.company.replace("Choi ceStream","ChoiceStream",inplace=True)
df.company.replace("ChoiceStream","ChoiceStream",inplace=True)
df.company.replace("ChosenList.com","ChosenList.com",inplace=True)
df.company.replace("Chumby","Chumby",inplace=True)
df.company.replace("Ciihui","Ciihui",inplace=True)
df.company.replace("Ciihui ","Ciihui",inplace=True)
df.company.replace("Cine maNow","CinemaNow",inplace=True)
df.company.replace("CircleUp","CircleUp",inplace=True)
df.company.replace("CitizenHawk","CitizenHawk",inplace=True)
df.company.replace("Cl earspring","Clearspring",inplace=True)
df.company.replace("Cl oud9 Analytics","Cloud9 Analytics",inplace=True)
df.company.replace("Clarizen","Clarizen",inplace=True)
df.company.replace("Cle verSet","CleverSet",inplace=True)
df.company.replace("Clearspring","Clearspring",inplace=True)
df.company.replace("Clearwell Systems","Clearwell Systems",inplace=True)
df.company.replace("CleverSet","CleverSet",inplace=True)
df.company.replace("Clic kability","Clickability",inplace=True)
df.company.replace("Click  Forensics","Click Forensics",inplace=True)
df.company.replace("Click Forensics","Click Forensics",inplace=True)
df.company.replace("Clickpass","Clickpass",inplace=True)
df.company.replace("Clupedia","Clupedia",inplace=True)
df.company.replace("Co ghead","Coghead",inplace=True)
df.company.replace("Co upa","Coupa",inplace=True)
df.company.replace("Co zi","Cozi",inplace=True)
df.company.replace("Codefast","Codefast",inplace=True)
df.company.replace("Cogent","Cogent Communications",inplace=True)
df.company.replace("Cogh ead","Coghead",inplace=True)
df.company.replace("Cognition Technologies","Cognition Technologies",inplace=True)
df.company.replace("Colizer","Colizer",inplace=True)
df.company.replace("Collarity","Collarity",inplace=True)
df.company.replace("Collec tive Intellect","Collective Intellect",inplace=True)
df.company.replace("Collective Intellect","Collective Intellect",inplace=True)
df.company.replace("Compendi um Blogware","Compendium Blogware",inplace=True)
df.company.replace("Compendium Blogware","Compendium Blogware",inplace=True)
df.company.replace("Compete","Compete.com",inplace=True)
df.company.replace("Cond uit","Conduit",inplace=True)
df.company.replace("CondoDomain","Condo Domain",inplace=True)
df.company.replace("Conduit","Conduit",inplace=True)
df.company.replace("Conduit Labs","Conduit Labs",inplace=True)
df.company.replace("Confabb","Confabb",inplace=True)
df.company.replace("Consorte Media","Consorte Media",inplace=True)
df.company.replace("Conte xtWeb","ContextWeb",inplace=True)
df.company.replace("Contex tWeb","ContextWeb",inplace=True)
df.company.replace("ContextWeb","ContextWeb",inplace=True)
df.company.replace("Cooki ng.com","Cooking.com",inplace=True)
df.company.replace("Cookin g.com","Cooking.com",inplace=True)
df.company.replace("Cooking.com","Cooking.com",inplace=True)
df.company.replace("Cooliri s","Cooliris",inplace=True)
df.company.replace("Core metrics","Coremetrics",inplace=True)
df.company.replace("Coremetrics","Coremetrics",inplace=True)
df.company.replace("Cosenti al","Cosential",inplace=True)
df.company.replace("Coupa","Coupa",inplace=True)
df.company.replace("Coveo","Coveo",inplace=True)
df.company.replace("Coverity","Coverity",inplace=True)
df.company.replace("Covestor","Covestor",inplace=True)
df.company.replace("Cozi","Cozi",inplace=True)
df.company.replace("Cr ackle","Crackle",inplace=True)
df.company.replace("Credi t Karma","Credit Karma",inplace=True)
df.company.replace("CriticalMetrics","Critical Metrics",inplace=True)
df.company.replace("CrossLoop","CrossLoop",inplace=True)
df.company.replace("Crunchyroll","Crunchyroll",inplace=True)
df.company.replace("Current Media","Current Media",inplace=True)
df.company.replace("Curse","Curse",inplace=True)
df.company.replace("Cutcaster","Cutcaster",inplace=True)
df.company.replace("DGP Lab s","DGP Labs",inplace=True)
df.company.replace("Da nger","Danger",inplace=True)
df.company.replace("Da tapipe","Datapipe",inplace=True)
df.company.replace("DailyStrength","DailyStrength",inplace=True)
df.company.replace("Dana l","Danal",inplace=True)
df.company.replace("DanceJam","Dancejam",inplace=True)
df.company.replace("Danger","Danger",inplace=True)
df.company.replace("Dapper","Dapper",inplace=True)
df.company.replace("Datran Media","Datran Media",inplace=True)
df.company.replace("Daylife ","Daylife ",inplace=True)
df.company.replace("Del ivery Agent","Delivery Agent",inplace=True)
df.company.replace("Del ve Networks","Delve Networks",inplace=True)
df.company.replace("Deli very Agent","Delivery Agent",inplace=True)
df.company.replace("Deliv ery Agent","Delivery Agent",inplace=True)
df.company.replace("Delve Networks","Delve Networks",inplace=True)
df.company.replace("Demand Media","Demand Media",inplace=True)
df.company.replace("Devi ceVM","DeviceVM",inplace=True)
df.company.replace("DeviceVM","DeviceVM",inplace=True)
df.company.replace("Di squs","Disqus",inplace=True)
df.company.replace("Dig g","Digg",inplace=True)
df.company.replace("Digg","Digg",inplace=True)
df.company.replace("Digital  Chocolate","Digital Chocolate",inplace=True)
df.company.replace("Digital Chocolate","Digital Chocolate",inplace=True)
df.company.replace("Digital Railroad","Digital Railroad",inplace=True)
df.company.replace("Dilit hium Networks","Dilithium Networks",inplace=True)
df.company.replace("Dilithium Networks","Dilithium Networks",inplace=True)
df.company.replace("Dimdi m","Dimdim",inplace=True)
df.company.replace("Dimdim","Dimdim",inplace=True)
df.company.replace("Dizzywood","Dizzywood",inplace=True)
df.company.replace("Docstoc","Docstoc",inplace=True)
df.company.replace("Docstoc ","Docstoc",inplace=True)
df.company.replace("DocuSign","DocuSign",inplace=True)
df.company.replace("Dogster","Dogster",inplace=True)
df.company.replace("Doostang","Doostang",inplace=True)
df.company.replace("Dr eamfactory","DreamFactory Software",inplace=True)
df.company.replace("Dr iftToIt","DriftToIt",inplace=True)
df.company.replace("Droplet Technology","Droplet Technology",inplace=True)
df.company.replace("Eart h Class Mail","Earth Class Mail",inplace=True)
df.company.replace("Earth C lass Mail","Earth Class Mail",inplace=True)
df.company.replace("EchoSign","EchoSign",inplace=True)
df.company.replace("Edge Cast","EdgeCast",inplace=True)
df.company.replace("Edge io","Edgeio",inplace=True)
df.company.replace("Elastra","Elastra Corporation",inplace=True)
df.company.replace("Endeca","Endeca",inplace=True)
df.company.replace("Endeca ","Endeca",inplace=True)
df.company.replace("EnergyWeb Solutions","EnergyWeb Solutions",inplace=True)
df.company.replace("Engine  Yard","Engine Yard",inplace=True)
df.company.replace("Ente rpriseDB","EnterpriseDB",inplace=True)
df.company.replace("Enterpr iseDB","EnterpriseDB",inplace=True)
df.company.replace("EnterpriseDB","EnterpriseDB",inplace=True)
df.company.replace("Ento ne Technologies","Entone Technologies",inplace=True)
df.company.replace("Entone Technologies","Entone Technologies",inplace=True)
df.company.replace("Entrecard","Entrecard",inplace=True)
df.company.replace("Eons","Eons",inplace=True)
df.company.replace("Estately","Estately",inplace=True)
df.company.replace("Etsy","Etsy",inplace=True)
df.company.replace("Eurekster","Eurekster",inplace=True)
df.company.replace("Event Vue","EventVue",inplace=True)
df.company.replace("EventVue","EventVue",inplace=True)
df.company.replace("Eventbrite","Eventbrite",inplace=True)
df.company.replace("Eventful","Eventful",inplace=True)
df.company.replace("Ever note","Evernote",inplace=True)
df.company.replace("Evernote","Evernote",inplace=True)
df.company.replace("Exinda","Exinda",inplace=True)
df.company.replace("Exp ertFlyer","ExpertFlyer",inplace=True)
df.company.replace("Experi ence Project","Experience Project",inplace=True)
df.company.replace("Eye-Fi","Eye-Fi",inplace=True)
df.company.replace("EyeJot","EyeJot",inplace=True)
df.company.replace("Eyeblaster","Eyeblaster",inplace=True)
df.company.replace("Fa cebook","Facebook",inplace=True)
df.company.replace("Faceb ook","Facebook",inplace=True)
df.company.replace("Facebook","Facebook",inplace=True)
df.company.replace("Facebook ","Facebook",inplace=True)
df.company.replace("FameCa st","FameCast",inplace=True)
df.company.replace("Farec ast","Farecast",inplace=True)
df.company.replace("Farecas t","Farecast",inplace=True)
df.company.replace("Farecast","Farecast",inplace=True)
df.company.replace("Fathom  Online","Fathom Online",inplace=True)
df.company.replace("Fav e Media","Fave Media",inplace=True)
df.company.replace("Fede rated Media","Federated Media",inplace=True)
df.company.replace("Federated Media","Federated Media",inplace=True)
df.company.replace("FeedBurner","FeedBurner",inplace=True)
df.company.replace("Fi ltrbox","Filtrbox",inplace=True)
df.company.replace("Fi refly Energy","Firefly Energy",inplace=True)
df.company.replace("Fi xYa","FixYa ",inplace=True)
df.company.replace("Fifth  Generation Systems","Fifth Generation Systems",inplace=True)
df.company.replace("Fifth G eneration Systems","Fifth Generation Systems",inplace=True)
df.company.replace("FilmLoop ","FilmLoop",inplace=True)
df.company.replace("Filtrbox","filtrbox",inplace=True)
df.company.replace("Fire fly Energy","Firefly Energy",inplace=True)
df.company.replace("Firefly Energy","Firefly Energy",inplace=True)
df.company.replace("Fix 8","Fix8",inplace=True)
df.company.replace("Fix8","Fix8",inplace=True)
df.company.replace("FixYa ","FixYa ",inplace=True)
df.company.replace("Fl owPlay","Flowplay",inplace=True)
df.company.replace("FlickIM","FlickIM",inplace=True)
df.company.replace("Flixster","Flixster",inplace=True)
df.company.replace("Flo ck","Flock",inplace=True)
df.company.replace("Floc k","Flock",inplace=True)
df.company.replace("Flock","Flock",inplace=True)
df.company.replace("FlowPlay","Flowplay",inplace=True)
df.company.replace("Fluid En tertainment","Fluid Entertainment",inplace=True)
df.company.replace("Flypap er","Flypaper",inplace=True)
df.company.replace("Fo ra.TV","Fora.tv",inplace=True)
df.company.replace("Fonemesh","Fonemesh",inplace=True)
df.company.replace("Fonemesh ","Fonemesh",inplace=True)
df.company.replace("Foneshow","Foneshow",inplace=True)
df.company.replace("Footnote","Footnote",inplace=True)
df.company.replace("Fortisphere","Fortisphere",inplace=True)
df.company.replace("FortiusOne","FortiusOne",inplace=True)
df.company.replace("Fr ame Media","Frame Media",inplace=True)
df.company.replace("Fr engo","Frengo",inplace=True)
df.company.replace("Fr iendster","Friendster",inplace=True)
df.company.replace("Frame  Media","Frame Media",inplace=True)
df.company.replace("Freew ebs","Freewebs",inplace=True)
df.company.replace("Frengo","Frengo",inplace=True)
df.company.replace("FriendF eed","FriendFeed",inplace=True)
df.company.replace("Friendster","Friendster",inplace=True)
df.company.replace("Fu nambol","Funambol",inplace=True)
df.company.replace("Funambol","Funambol",inplace=True)
df.company.replace("Funambol ","Funambol",inplace=True)
df.company.replace("Funny Or Die","Funny Or Die",inplace=True)
df.company.replace("FusionOps","FusionOps",inplace=True)
df.company.replace("Fynan z","Fynanz",inplace=True)
df.company.replace("Fyreball","Fyreball",inplace=True)
df.company.replace("GROU. PS","GROU.PS",inplace=True)
df.company.replace("Ga ia","Gaia",inplace=True)
df.company.replace("Gaia","Gaia",inplace=True)
df.company.replace("GameLayers","GameLayers",inplace=True)
df.company.replace("GamerDNA","GamerDNA",inplace=True)
df.company.replace("Gamook","Gamook",inplace=True)
df.company.replace("GarageGames","GarageGames",inplace=True)
df.company.replace("Ge mini","Gemini",inplace=True)
df.company.replace("Geezeo","Geezeo",inplace=True)
df.company.replace("Gemini","Gemini",inplace=True)
df.company.replace("Gen ius","Genius",inplace=True)
df.company.replace("GenArts","GenArts",inplace=True)
df.company.replace("Geni","Geni",inplace=True)
df.company.replace("Geni eTown","GenieTown",inplace=True)
df.company.replace("Genius","Genius",inplace=True)
df.company.replace("Get Satisfaction","Get Satisfaction",inplace=True)
df.company.replace("Gi zmoz","Gizmoz",inplace=True)
df.company.replace("Giga O mni Media","Giga Omni Media",inplace=True)
df.company.replace("Gigya","Gigya",inplace=True)
df.company.replace("GizmoProject","GizmoProject",inplace=True)
df.company.replace("Gizmoz","Gizmoz",inplace=True)
df.company.replace("Gla m Media","Glam Media",inplace=True)
df.company.replace("Glam Media","Glam Media",inplace=True)
df.company.replace("Glassdoor","Glassdoor",inplace=True)
df.company.replace("Global  Grind","Global  Grind",inplace=True)
df.company.replace("Global Roaming","Global Roaming",inplace=True)
df.company.replace("Gn ip","Gnip",inplace=True)
df.company.replace("Go od Data","Good Data",inplace=True)
df.company.replace("GoCrossC ampus","GoCrossCampus",inplace=True)
df.company.replace("GodTub e","GodTube",inplace=True)
df.company.replace("Goi ngOn","GoingOn",inplace=True)
df.company.replace("Goin g","Going",inplace=True)
df.company.replace("GoldSpot Media","GoldSpot Media",inplace=True)
df.company.replace("GoodReads","GoodReads",inplace=True)
df.company.replace("Googl e","Google",inplace=True)
df.company.replace("GotVoice","GotVoice",inplace=True)
df.company.replace("Gotui t Media","Gotuit Media",inplace=True)
df.company.replace("Gotuit Media","Gotuit Media",inplace=True)
df.company.replace("Gr ubHub","GrubHub",inplace=True)
df.company.replace("Graspr","Graspr",inplace=True)
df.company.replace("Gre enplum","Greenplum",inplace=True)
df.company.replace("Great Call","GreatCall",inplace=True)
df.company.replace("Gree nplum","Greenplum",inplace=True)
df.company.replace("GreenNo te","GreenNote",inplace=True)
df.company.replace("Greenplum","Greenplum",inplace=True)
df.company.replace("Greystripe","Greystripe",inplace=True)
df.company.replace("Grid Networks","Grid Networks",inplace=True)
df.company.replace("GridNetworks","Grid Networks",inplace=True)
df.company.replace("GridPoint","GridPoint",inplace=True)
df.company.replace("Gridstone Research","Gridstone Research",inplace=True)
df.company.replace("Gro uply","Grouply",inplace=True)
df.company.replace("Grockit","Grockit",inplace=True)
df.company.replace("Grou ply","Grouply",inplace=True)
df.company.replace("Grouply","Grouply",inplace=True)
df.company.replace("Grouptivity","Grouptivity",inplace=True)
df.company.replace("Guardi an Analytics","Guardian Analytics",inplace=True)
df.company.replace("GumGum","GumGum",inplace=True)
df.company.replace("Gydget","Gydget",inplace=True)
df.company.replace("HAM-IT","HAM-IT",inplace=True)
df.company.replace("HEXIO","HEXIO",inplace=True)
df.company.replace("Habit I ndustries","Habit Industries",inplace=True)
df.company.replace("Hand ipoints","Handipoints",inplace=True)
df.company.replace("Haute Secure","Haute Secure",inplace=True)
df.company.replace("Health Plan One","Health Plan One",inplace=True)
df.company.replace("HealthCentral","HealthCentral",inplace=True)
df.company.replace("Healthli ne","Healthline",inplace=True)
df.company.replace("Healthline","Healthline",inplace=True)
df.company.replace("Heavy.com","Heavy.com",inplace=True)
df.company.replace("HelioVolt","HelioVolt",inplace=True)
df.company.replace("Heroku","Heroku",inplace=True)
df.company.replace("Heroku ","Heroku",inplace=True)
df.company.replace("Heysan","Heysan",inplace=True)
df.company.replace("Hive Live","Hive Live",inplace=True)
df.company.replace("HiveLive","Hive Live",inplace=True)
df.company.replace("Hooja","Hooja",inplace=True)
df.company.replace("HotPads","HotPads",inplace=True)
df.company.replace("HubSpo t","HubSpot",inplace=True)
df.company.replace("HubSpot","HubSpot",inplace=True)
df.company.replace("Hy phen 8","Hyphen-8",inplace=True)
df.company.replace("Hyp eric","Hyperic",inplace=True)
df.company.replace("IG A Worldwide","IGA Worldwide",inplace=True)
df.company.replace("IGA Worl dwide","IGA Worldwide",inplace=True)
df.company.replace("IGA Worldwide","IGA Worldwide",inplace=True)
df.company.replace("IMVU","IMVU",inplace=True)
df.company.replace("Ideeli","Ideeli",inplace=True)
df.company.replace("If byphone","Ifbyphone",inplace=True)
df.company.replace("ImageSpan","ImageSpan",inplace=True)
df.company.replace("InGrid","InGrid",inplace=True)
df.company.replace("InMag e Systems","InMage Systems",inplace=True)
df.company.replace("InThrMa","InThrMa",inplace=True)
df.company.replace("Indeed","Indeed",inplace=True)
df.company.replace("Infinia","Infinia",inplace=True)
df.company.replace("Infinity Box","Infinity Box",inplace=True)
df.company.replace("Info","Info",inplace=True)
df.company.replace("Infusionsoft","Infusionsoft",inplace=True)
df.company.replace("Inkling","Inkling",inplace=True)
df.company.replace("Insid eView","InsideView",inplace=True)
df.company.replace("Insider Pages","Insider Pages",inplace=True)
df.company.replace("Inst inctiv","Instinctiv",inplace=True)
df.company.replace("Insta garage","Instagarage",inplace=True)
df.company.replace("Int elliworks","Intelliworks",inplace=True)
df.company.replace("Int ernational Liars Poker Association","International Liar's Poker Association",inplace=True)
df.company.replace("Intac ct","Intacct",inplace=True)
df.company.replace("Intacct","Intacct",inplace=True)
df.company.replace("Intelliworks","Intelliworks",inplace=True)
df.company.replace("Intense Debate","Intense Debate",inplace=True)
df.company.replace("Intent","Intent",inplace=True)
df.company.replace("Interneer","Interneer",inplace=True)
df.company.replace("Intronis","Intronis",inplace=True)
df.company.replace("Invense nse","InvenSense",inplace=True)
df.company.replace("J Squared Media","J-Squared Media",inplace=True)
df.company.replace("JAD  Tech Consulting","JAD Tech Consulting",inplace=True)
df.company.replace("Ja ngl","Jangl",inplace=True)
df.company.replace("Ja xtr","Jaxtr",inplace=True)
df.company.replace("JackBe","JackBe",inplace=True)
df.company.replace("JackPot Rewards","Jackpot Rewards",inplace=True)
df.company.replace("Jajah","Jajah",inplace=True)
df.company.replace("Jaxtr","Jaxtr",inplace=True)
df.company.replace("Jaxtr ","Jaxtr",inplace=True)
df.company.replace("JellyCloud","JellyCloud",inplace=True)
df.company.replace("Ji ngle Networks","Jingle Networks",inplace=True)
df.company.replace("Ji ve Software","Jive Software",inplace=True)
df.company.replace("JibJab","JibJab",inplace=True)
df.company.replace("Jigsaw","Jigsaw",inplace=True)
df.company.replace("Jingle Networks","Jingle Networks",inplace=True)
df.company.replace("Jivox","Jivox",inplace=True)
df.company.replace("Jobfox","Jobfox",inplace=True)
df.company.replace("Jobst er","Jobster",inplace=True)
df.company.replace("Jobster","Jobster",inplace=True)
df.company.replace("Jobvit e","Jobvite",inplace=True)
df.company.replace("JotSp ot","JotSpot ",inplace=True)
df.company.replace("Jott","Jott",inplace=True)
df.company.replace("Ju ice Wireless","Juice Wireless",inplace=True)
df.company.replace("Judys  Book","Judys Book",inplace=True)
df.company.replace("Judys Book","Judys Book",inplace=True)
df.company.replace("Juic e Wireless","Juice Wireless",inplace=True)
df.company.replace("Juice  Wireless","Juice Wireless",inplace=True)
df.company.replace("Juice Wireless","Juice Wireless",inplace=True)
df.company.replace("KIT digital","KIT Digital",inplace=True)
df.company.replace("Kabo odle","Kaboodle",inplace=True)
df.company.replace("Kabood le","Kaboodle",inplace=True)
df.company.replace("Kaboodle","Kaboodle",inplace=True)
df.company.replace("Kaltura","Kaltura",inplace=True)
df.company.replace("Kapow Te chnologies","Kapow Technologies",inplace=True)
df.company.replace("Kapow Technologies","Kapow Technologies",inplace=True)
df.company.replace("Katalyst Media","Katalyst Media",inplace=True)
df.company.replace("Kayak","Kayak",inplace=True)
df.company.replace("Kei bi Technologies","Keibi Technologies",inplace=True)
df.company.replace("Kip tronic","Kiptronic",inplace=True)
df.company.replace("Kiptronic","Kiptronic",inplace=True)
df.company.replace("Kluster","Kluster",inplace=True)
df.company.replace("Knewt on","Knewton",inplace=True)
df.company.replace("Kon gregate","Kongregate",inplace=True)
df.company.replace("Kongreg ate","Kongregate",inplace=True)
df.company.replace("Kongregate","Kongregate",inplace=True)
df.company.replace("Kontera","Kontera",inplace=True)
df.company.replace("Kosmix ","Kosmix",inplace=True)
df.company.replace("Kyte","Kyte",inplace=True)
df.company.replace("Labmeeti ng","Labmeeting",inplace=True)
df.company.replace("Lala","Lala",inplace=True)
df.company.replace("Laszlo S ystems","Laszlo Systems",inplace=True)
df.company.replace("Laszlo Systems","Laszlo Systems",inplace=True)
df.company.replace("Lau nchBox","LaunchBox",inplace=True)
df.company.replace("Lehigh Technologies","Lehigh Technologies",inplace=True)
df.company.replace("Lending Club","Lending Club",inplace=True)
df.company.replace("Leverage  Software","Leverage Software",inplace=True)
df.company.replace("Li feLock","LifeLock",inplace=True)
df.company.replace("Li meLife","Limelife",inplace=True)
df.company.replace("Li nkedIn","LinkedIn",inplace=True)
df.company.replace("Li veMocha","Livemocha",inplace=True)
df.company.replace("LicketyShip","LicketyShip",inplace=True)
df.company.replace("LifeL ock","LifeLock",inplace=True)
df.company.replace("LifeLock","LifeLock",inplace=True)
df.company.replace("Lijit","Lijit",inplace=True)
df.company.replace("Limbo","Limbo",inplace=True)
df.company.replace("LimeLi fe","LimeLife",inplace=True)
df.company.replace("LimeLife","LimeLife",inplace=True)
df.company.replace("Limea de","Limeade",inplace=True)
df.company.replace("LinkedIn","LinkedIn",inplace=True)
df.company.replace("LinkedIn ","LinkedIn",inplace=True)
df.company.replace("Liq uidPlanner","LiquidPlanner",inplace=True)
df.company.replace("Lithiu m Technologies","Lithium Technologies",inplace=True)
df.company.replace("Lithium  Technologies","Lithium Technologies",inplace=True)
df.company.replace("Live Gamer","Live Gamer",inplace=True)
df.company.replace("LiveDeal ","LiveDeal",inplace=True)
df.company.replace("LiveO ps","LiveOps",inplace=True)
df.company.replace("LiveOp s","LiveOps",inplace=True)
df.company.replace("Lo okery","Lookery",inplace=True)
df.company.replace("Loladex","Loladex",inplace=True)
df.company.replace("Loom ia","Loomia",inplace=True)
df.company.replace("Loomia","Loomia",inplace=True)
df.company.replace("Loopt","Loopt",inplace=True)
df.company.replace("Loud Click","Loud Click",inplace=True)
df.company.replace("Lu mos Labs","Lumos Labs",inplace=True)
df.company.replace("Lumos Labs","Lumos Labs",inplace=True)
df.company.replace("M:Metrics","M:Metrics",inplace=True)
df.company.replace("MFG","MFG.com",inplace=True)
df.company.replace("MOG","MOG Technologies",inplace=True)
df.company.replace("MOLI","MOLI",inplace=True)
df.company.replace("MPTrax","MPTrax",inplace=True)
df.company.replace("Ma halo","Mahalo",inplace=True)
df.company.replace("Mad Mimi","Mad Mimi",inplace=True)
df.company.replace("Mahalo","Mahalo",inplace=True)
df.company.replace("Mari n Software","Marin Software",inplace=True)
df.company.replace("Marin Software","Marin Software",inplace=True)
df.company.replace("MarketLive","MarketLive",inplace=True)
df.company.replace("Mashery","Mashery",inplace=True)
df.company.replace("MatchMine","MatchMine",inplace=True)
df.company.replace("Me","Me",inplace=True)
df.company.replace("Me eVee","MeeVee",inplace=True)
df.company.replace("Me raki","Meraki",inplace=True)
df.company.replace("Me.dium","Me.dium",inplace=True)
df.company.replace("Media  Lantern","Media Lantern",inplace=True)
df.company.replace("Media  Machines","Media Machines",inplace=True)
df.company.replace("Media6Â¡","Media6Â¡",inplace=True)
df.company.replace("Mee bo","Meebo",inplace=True)
df.company.replace("MeeVee","MeeVee",inplace=True)
df.company.replace("Meebo","Meebo",inplace=True)
df.company.replace("MeetMoi","MeetMoi",inplace=True)
df.company.replace("Meetu p","Meetup",inplace=True)
df.company.replace("Meetup","Meetup",inplace=True)
df.company.replace("Mefeedia","MeFeedia",inplace=True)
df.company.replace("Memeo","Memeo",inplace=True)
df.company.replace("Meraki","Meraki",inplace=True)
df.company.replace("Mercent Corporation","Mercent Corporation",inplace=True)
df.company.replace("MerchantCircle","MerchantCircle",inplace=True)
df.company.replace("Mercor a","Mercora",inplace=True)
df.company.replace("Met acafe","Metacafe",inplace=True)
df.company.replace("Metacafe","Metacafe",inplace=True)
df.company.replace("Metaweb Technologies","Metaweb Technologies",inplace=True)
df.company.replace("Mevi o","Mevio",inplace=True)
df.company.replace("Mevio","Mevio",inplace=True)
df.company.replace("Mi xx","Mixx",inplace=True)
df.company.replace("Mil l River Labs","Mill River Labs",inplace=True)
df.company.replace("Mimeo","Mimeo",inplace=True)
df.company.replace("Min t","Mint",inplace=True)
df.company.replace("Minekey","Minekey",inplace=True)
df.company.replace("Mint","Mint",inplace=True)
df.company.replace("Minted","Minted",inplace=True)
df.company.replace("Mix &  Meet","Mix & Meet",inplace=True)
df.company.replace("Mixercast","Mixercast",inplace=True)
df.company.replace("Mixx","Mixx",inplace=True)
df.company.replace("Mo chi Media","Mochi Media",inplace=True)
df.company.replace("Mo xsie","Moxsie",inplace=True)
df.company.replace("MoGreet","MoGreet",inplace=True)
df.company.replace("MoGreet ","MoGreet",inplace=True)
df.company.replace("Mobissimo","Mobissimo",inplace=True)
df.company.replace("Mobixell","Mobixell",inplace=True)
df.company.replace("Moblyng","Moblyng",inplace=True)
df.company.replace("Moblyng ","Moblyng",inplace=True)
df.company.replace("Moch ila","Mochila",inplace=True)
df.company.replace("Mochi Media","Mochi Media",inplace=True)
df.company.replace("Moco Space","MocoSpace",inplace=True)
df.company.replace("Modern Feed","Modern Feed",inplace=True)
df.company.replace("Mogad","Mogad",inplace=True)
df.company.replace("Mogul us","Mogulus",inplace=True)
df.company.replace("Mogulus","Mogulus",inplace=True)
df.company.replace("Mogulus ","Mogulus",inplace=True)
df.company.replace("Motionbox","Motionbox",inplace=True)
df.company.replace("Mov e Networks","Move Networks",inplace=True)
df.company.replace("Move Networks","Move Networks",inplace=True)
df.company.replace("Mozes","Mozes",inplace=True)
df.company.replace("Mozilla ","Mozilla",inplace=True)
df.company.replace("Mozy","Mozy",inplace=True)
df.company.replace("Mu ltiply","Multiply",inplace=True)
df.company.replace("Multi verse","Multiverse",inplace=True)
df.company.replace("Multiply","Multiply",inplace=True)
df.company.replace("Multiverse","Multiverse",inplace=True)
df.company.replace("Mumbo e","Mumboe",inplace=True)
df.company.replace("MuseStorm","MuseStorm",inplace=True)
df.company.replace("MyB uys","MyBuys",inplace=True)
df.company.replace("MyBuy s","MyBuys",inplace=True)
df.company.replace("MyCityFaces","MyCityFaces",inplace=True)
df.company.replace("MyS QL","MySQL",inplace=True)
df.company.replace("MySQL","MySQL",inplace=True)
df.company.replace("MyThi ngs","myThings",inplace=True)
df.company.replace("Myrio","Myrio",inplace=True)
df.company.replace("Mzinga","Mzinga",inplace=True)
df.company.replace("Nanosolar","Nanosolar",inplace=True)
df.company.replace("Nav ic Networks","Navic Networks",inplace=True)
df.company.replace("Navi c Networks","Navic Networks",inplace=True)
df.company.replace("Navic Networks","Navic Networks",inplace=True)
df.company.replace("Ne xt New Networks","Next New Networks",inplace=True)
df.company.replace("NeoEdge  Networks","NeoEdge Networks",inplace=True)
df.company.replace("Neocleus","Neocleus",inplace=True)
df.company.replace("Netcipia","Netcipia",inplace=True)
df.company.replace("NeuroVigil","NeuroVigil",inplace=True)
df.company.replace("New Relic","New Relic",inplace=True)
df.company.replace("News Gator","NewsGator",inplace=True)
df.company.replace("NewsGa tor","NewsGator",inplace=True)
df.company.replace("NewsGator","NewsGator",inplace=True)
df.company.replace("Newsvine","Newsvine",inplace=True)
df.company.replace("Next  New Networks","Next New Networks",inplace=True)
df.company.replace("Ni ng","Ning",inplace=True)
df.company.replace("Nile Gui de","NileGuide",inplace=True)
df.company.replace("Ning","Ning",inplace=True)
df.company.replace("Nirvanix ","Nirvanix",inplace=True)
df.company.replace("Novint","Novint",inplace=True)
df.company.replace("Ntracti ve","Ntractive",inplace=True)
df.company.replace("Numobiq","Numobiq",inplace=True)
df.company.replace("OLX","OLX",inplace=True)
df.company.replace("ON24","ON24",inplace=True)
df.company.replace("Omnidri ve","OmniDrive",inplace=True)
df.company.replace("On  Networks","ON Networks",inplace=True)
df.company.replace("On Networks","ON Networks",inplace=True)
df.company.replace("OnFor ce","OnForce",inplace=True)
df.company.replace("OnForc e","OnForce",inplace=True)
df.company.replace("Oodl e","Oodle",inplace=True)
df.company.replace("Oodle","Oodle",inplace=True)
df.company.replace("Ooyala","Ooyala",inplace=True)
df.company.replace("Op taros","Optaros",inplace=True)
df.company.replace("Ope nDNS","OpenDNS",inplace=True)
df.company.replace("OpenTable","OpenTable",inplace=True)
df.company.replace("Optar os","Optaros",inplace=True)
df.company.replace("Optaros","Optaros",inplace=True)
df.company.replace("OrderMotion","OrderMotion",inplace=True)
df.company.replace("Organize dWisdom","OrganizedWisdom",inplace=True)
df.company.replace("OurStory","OurStory",inplace=True)
df.company.replace("Outbrain","Outbrain",inplace=True)
df.company.replace("Outs ide.in","Outside.in",inplace=True)
df.company.replace("Outside. in","Outside.in",inplace=True)
df.company.replace("Outside.in","Outside.in",inplace=True)
df.company.replace("Outsp ark","Outspark",inplace=True)
df.company.replace("Outspark","Outspark",inplace=True)
df.company.replace("OverSee","OverSee",inplace=True)
df.company.replace("OverSee ","OverSee",inplace=True)
df.company.replace("Ozmo  Devices","Ozmo Devices",inplace=True)
df.company.replace("PL Ymedia","PLYmedia",inplace=True)
df.company.replace("PLYmedia","PLYmedia",inplace=True)
df.company.replace("Pa rascale","Parascale",inplace=True)
df.company.replace("Pag eflakes","Pageflakes",inplace=True)
df.company.replace("Pageonce","PageOnce",inplace=True)
df.company.replace("Pan do","Pando",inplace=True)
df.company.replace("Pando","Pando",inplace=True)
df.company.replace("Pando ra","Pandora",inplace=True)
df.company.replace("Pandor a","Pandora",inplace=True)
df.company.replace("Pandora","Pandora",inplace=True)
df.company.replace("Pange a Media","Pangea Media",inplace=True)
df.company.replace("Par ature","Parature",inplace=True)
df.company.replace("Parature","Parature",inplace=True)
df.company.replace("Passenger","Passenger",inplace=True)
df.company.replace("Paxfire ","Paxfire",inplace=True)
df.company.replace("Pay Pal","PayPal",inplace=True)
df.company.replace("Pay Scale","PayScale",inplace=True)
df.company.replace("PayPa l","PayPal",inplace=True)
df.company.replace("PayPal","PayPal",inplace=True)
df.company.replace("PayPer Post","PayPerPost",inplace=True)
df.company.replace("PayPerPost","PayPerPost",inplace=True)
df.company.replace("PaySca le","PayScale",inplace=True)
df.company.replace("PayScale","PayScale",inplace=True)
df.company.replace("Paymo","Paymo",inplace=True)
df.company.replace("Payoneer","Payoneer",inplace=True)
df.company.replace("Pee r39","Peer39",inplace=True)
df.company.replace("Peer39","Peer39",inplace=True)
df.company.replace("PeerMe","PeerMe",inplace=True)
df.company.replace("Peerfli x","Peerflix",inplace=True)
df.company.replace("Pelago","Pelago",inplace=True)
df.company.replace("Perfect Market","Perfect Market",inplace=True)
df.company.replace("PermissionTV","PermissionTV",inplace=True)
df.company.replace("Pha nfare","Phanfare",inplace=True)
df.company.replace("Phanfare","Phanfare",inplace=True)
df.company.replace("Pho toCrank","PhotoCrank",inplace=True)
df.company.replace("Phon eTag","PhoneTag",inplace=True)
df.company.replace("PhoneT ag","PhoneTag",inplace=True)
df.company.replace("Phonezoo","Phonezoo",inplace=True)
df.company.replace("Photobucket","Photobucket",inplace=True)
df.company.replace("PicksPal","PicksPal",inplace=True)
df.company.replace("Piczo","Piczo",inplace=True)
df.company.replace("Ping er","Pinger",inplace=True)
df.company.replace("Pingg","Pingg",inplace=True)
df.company.replace("Pingg ","Pingg",inplace=True)
df.company.replace("Piv ot","Pivot",inplace=True)
df.company.replace("Pivot","Pivot",inplace=True)
df.company.replace("PixSen se","PixSense",inplace=True)
df.company.replace("PixSense","PixSense",inplace=True)
df.company.replace("Pixim","Pixim",inplace=True)
df.company.replace("Pixim ","Pixim",inplace=True)
df.company.replace("Plastic Logic","Plastic Logic",inplace=True)
df.company.replace("Platial","Platial",inplace=True)
df.company.replace("Plax o","Plaxo",inplace=True)
df.company.replace("Plaxo","Plaxo",inplace=True)
df.company.replace("Play Span","PlaySpan",inplace=True)
df.company.replace("PlayFi rst","PlayFirst",inplace=True)
df.company.replace("PlayFirs t","PlayFirst",inplace=True)
df.company.replace("Pluck","Pluck",inplace=True)
df.company.replace("PluggedIn","PluggedIn",inplace=True)
df.company.replace("Po ntiflex","Pontiflex",inplace=True)
df.company.replace("PodTe ch","PodTech",inplace=True)
df.company.replace("PodTech","PodTech",inplace=True)
df.company.replace("PopularM edia","PopularMedia",inplace=True)
df.company.replace("PopularMedia","PopularMedia",inplace=True)
df.company.replace("Posterous","Posterous",inplace=True)
df.company.replace("Pow erReview","PowerReviews",inplace=True)
df.company.replace("Pow erset","Powerset",inplace=True)
df.company.replace("PowerReview","PowerReviews",inplace=True)
df.company.replace("Predic tify","Predictify",inplace=True)
df.company.replace("PrepChamps","PrepChamps",inplace=True)
df.company.replace("Presdo","Presdo",inplace=True)
df.company.replace("ProgrammerMeetDesigner.com","ProgrammerMeetDesigner.com",inplace=True)
df.company.replace("Project Playlist","Project Playlist",inplace=True)
df.company.replace("Pros per","Prosper",inplace=True)
df.company.replace("Prosper","Prosper",inplace=True)
df.company.replace("PubMatic","PubMatic",inplace=True)
df.company.replace("Pudding  Media","Pudding Media",inplace=True)
df.company.replace("Pure Video Networks","PureVideo Networks",inplace=True)
df.company.replace("PureVideo Networks","PureVideo Networks",inplace=True)
df.company.replace("Qik","Qik",inplace=True)
df.company.replace("Qpo nDirect","QponDirect",inplace=True)
df.company.replace("Qu ickoffice","Quickoffice",inplace=True)
df.company.replace("Quante nna","Quantenna",inplace=True)
df.company.replace("Quattro Wireless","Quattro Wireless",inplace=True)
df.company.replace("Quickoffice","Quickoffice",inplace=True)
df.company.replace("Quigo","Quigo",inplace=True)
df.company.replace("Qumu","Qumu ",inplace=True)
df.company.replace("Qwaq","Qwaq",inplace=True)
df.company.replace("Radar Ne tworks","Radar Networks",inplace=True)
df.company.replace("Radar Networks","Radar Networks",inplace=True)
df.company.replace("Ral ly Software","Rally Software",inplace=True)
df.company.replace("RatePoint","RatePoint",inplace=True)
df.company.replace("RayV","RayV",inplace=True)
df.company.replace("RazorGator","RazorGator",inplace=True)
df.company.replace("Re dfin","Redfin",inplace=True)
df.company.replace("Re mixation","Remixation",inplace=True)
df.company.replace("Re trevo","Retrevo",inplace=True)
df.company.replace("Real ity Digital","Reality Digital",inplace=True)
df.company.replace("RealSe lf","RealSelf",inplace=True)
df.company.replace("Reality  Digital","Reality Digital",inplace=True)
df.company.replace("Realius","Realius",inplace=True)
df.company.replace("Rebel Monkey","Rebel Monkey",inplace=True)
df.company.replace("RedLasso","RedLasso",inplace=True)
df.company.replace("Reddit","Reddit",inplace=True)
df.company.replace("Redfi n","Redfin",inplace=True)
df.company.replace("Redfin","Redfin",inplace=True)
df.company.replace("Redux","Redux",inplace=True)
df.company.replace("RescueTime","RescueTime",inplace=True)
df.company.replace("Respectance","Respectance",inplace=True)
df.company.replace("Respon seLogix","ResponseLogix",inplace=True)
df.company.replace("Retai l Convergence","Retail Convergence",inplace=True)
df.company.replace("Retrevo","Retrevo",inplace=True)
df.company.replace("Reunio n","Reunion",inplace=True)
df.company.replace("RevenueScience","Revenue Science",inplace=True)
df.company.replace("Revis ion3","Revision3",inplace=True)
df.company.replace("Revision3","Revision3",inplace=True)
df.company.replace("Revolu tion Money","Revolution Money",inplace=True)
df.company.replace("Revver","Revver",inplace=True)
df.company.replace("Revver ","Revver",inplace=True)
df.company.replace("Rib bit","Ribbit",inplace=True)
df.company.replace("Ribbit","Ribbit",inplace=True)
df.company.replace("RingC entral","RingCentral",inplace=True)
df.company.replace("RingCentral","RingCentral",inplace=True)
df.company.replace("Ripl","Ripl",inplace=True)
df.company.replace("RiverWired","RiverWired",inplace=True)
df.company.replace("Ro toHog","RotoHog",inplace=True)
df.company.replace("RoboDyn amics","RoboDynamics",inplace=True)
df.company.replace("RoboDynamics","RoboDynamics",inplace=True)
df.company.replace("Rock You","RockYou",inplace=True)
df.company.replace("RockYou","RockYou",inplace=True)
df.company.replace("RocketOn","RocketOn",inplace=True)
df.company.replace("Rollbase ","Rollbase",inplace=True)
df.company.replace("RooftopComedy","Rooftop Comedy",inplace=True)
df.company.replace("Rosum","Rosum",inplace=True)
df.company.replace("Row44","Row44",inplace=True)
df.company.replace("Rub icon Project","Rubicon Project",inplace=True)
df.company.replace("Rubicon Project","Rubicon Project",inplace=True)
df.company.replace("Rupture","Rupture",inplace=True)
df.company.replace("SAVO","SAVO",inplace=True)
df.company.replace("SEOM oz","SEOMoz",inplace=True)
df.company.replace("Sampa","Sampa",inplace=True)
df.company.replace("SayNo w","SayNow",inplace=True)
df.company.replace("Sc ribd","Scribd",inplace=True)
df.company.replace("ScanScout","ScanScout",inplace=True)
df.company.replace("Scanbuy","Scanbuy",inplace=True)
df.company.replace("Scanbuy ","Scanbuy",inplace=True)
df.company.replace("Scintella Solutions","Scintella Solutions",inplace=True)
df.company.replace("Screami ng Sports","Screaming Sports",inplace=True)
df.company.replace("Scri beStorm","ScribeStorm",inplace=True)
df.company.replace("Scribd ","Scribd",inplace=True)
df.company.replace("Sea rchMe","SearchMe",inplace=True)
df.company.replace("Sear chMe","SearchMe",inplace=True)
df.company.replace("Searc hMe","SearchMe",inplace=True)
df.company.replace("Search to Phone","Search to Phone",inplace=True)
df.company.replace("SearchMe","SearchMe",inplace=True)
df.company.replace("Searchles","Searchles",inplace=True)
df.company.replace("SeeToo","SeeToo",inplace=True)
df.company.replace("Seeqpod","SeeqPod",inplace=True)
df.company.replace("Sel lPoint","sellpoint",inplace=True)
df.company.replace("SelectMinds","SelectMinds",inplace=True)
df.company.replace("Send Me","SendMe",inplace=True)
df.company.replace("SendMe ","SendMe",inplace=True)
df.company.replace("Sense Networks","Sense Networks",inplace=True)
df.company.replace("Serious Business","Serious Business",inplace=True)
df.company.replace("Sermo","Sermo",inplace=True)
df.company.replace("Service-now.com","Service-now.com",inplace=True)
df.company.replace("SezWho","SezWho",inplace=True)
df.company.replace("Sh arpcast","Sharpcast",inplace=True)
df.company.replace("Sh opflick","Shopflick",inplace=True)
df.company.replace("Shangby","ShangBy",inplace=True)
df.company.replace("Sharpcast","Sharpcast",inplace=True)
df.company.replace("Sho utWire","ShoutWire",inplace=True)
df.company.replace("Shopfli ck","Shopflick",inplace=True)
df.company.replace("ShowCli x","ShowClix",inplace=True)
df.company.replace("ShowClix","ShowClix",inplace=True)
df.company.replace("Shozu","ShoZu",inplace=True)
df.company.replace("SiBEAM","SiBeam",inplace=True)
df.company.replace("Sid eStep","SideStep",inplace=True)
df.company.replace("Side Step","SideStep",inplace=True)
df.company.replace("SideS tep","SideStep",inplace=True)
df.company.replace("SideStep","SideStep",inplace=True)
df.company.replace("Silicon Alley Insider","Silicon Alley Insider",inplace=True)
df.company.replace("SilkR oad technology","SilkRoad Technology",inplace=True)
df.company.replace("SilkRoad technology","SilkRoad Technology",inplace=True)
df.company.replace("Simpl eTuition","SimpleTuition",inplace=True)
df.company.replace("SimpleTuition","SimpleTuition",inplace=True)
df.company.replace("SimplyHired","Simply Hired",inplace=True)
df.company.replace("Sirtris  Pharmaceuticals","Sirtris Pharmaceuticals",inplace=True)
df.company.replace("Sirtris Pharmaceuticals","Sirtris Pharmaceuticals",inplace=True)
df.company.replace("Six  Apart","Six Apart",inplace=True)
df.company.replace("Six Ap art","Six Apart",inplace=True)
df.company.replace("Six Apart","Six Apart",inplace=True)
df.company.replace("SkyGrid","SkyGrid",inplace=True)
df.company.replace("Skyfi re","Skyfire",inplace=True)
df.company.replace("Skyfire","Skyfire",inplace=True)
df.company.replace("Sla cker","Slacker",inplace=True)
df.company.replace("Slacker ","Slacker",inplace=True)
df.company.replace("Sleep.FM","Sleep.FM",inplace=True)
df.company.replace("Slide","Slide",inplace=True)
df.company.replace("SlideRoc ket","SlideRocket",inplace=True)
df.company.replace("SlideShare","SlideShare",inplace=True)
df.company.replace("Slin g Media","Sling Media",inplace=True)
df.company.replace("Sling Media","Sling Media",inplace=True)
df.company.replace("Sling page","Slingpage",inplace=True)
df.company.replace("Smaato","Smaato",inplace=True)
df.company.replace("Small World Labs","Small World Labs",inplace=True)
df.company.replace("Smalltown","Smalltown",inplace=True)
df.company.replace("SmartSh eet","Smartsheet",inplace=True)
df.company.replace("Smilebox","Smilebox",inplace=True)
df.company.replace("Snap Technologies","Snap Technology",inplace=True)
df.company.replace("Snap vine","Snapvine",inplace=True)
df.company.replace("SnapLa yout","SnapLayout",inplace=True)
df.company.replace("SnapLogic","SnapLogic",inplace=True)
df.company.replace("Snapfish","Snapfish",inplace=True)
df.company.replace("Snapvin e","Snapvine",inplace=True)
df.company.replace("Snooth","Snooth",inplace=True)
df.company.replace("So cial Gaming Network","Social Gaming Network",inplace=True)
df.company.replace("So cialVibe","SocialVibe",inplace=True)
df.company.replace("Social Media","Social Median",inplace=True)
df.company.replace("Social Median","Social Median",inplace=True)
df.company.replace("Socializr","Socializr",inplace=True)
df.company.replace("Socialt ext","Socialtext",inplace=True)
df.company.replace("Socialtext","Socialtext",inplace=True)
df.company.replace("Socialthing!","Socialthing",inplace=True)
df.company.replace("Soda Head","SodaHead",inplace=True)
df.company.replace("SodaHead ","SodaHead",inplace=True)
df.company.replace("Solarflare","Solarflare",inplace=True)
df.company.replace("Someecar ds","Someecards",inplace=True)
df.company.replace("Sometrics","Sometrics",inplace=True)
df.company.replace("Songbird","Songbird",inplace=True)
df.company.replace("Sp here","Sphere",inplace=True)
df.company.replace("Sp iralFrog","SpiralFrog",inplace=True)
df.company.replace("Spa Boom","SpaBoom",inplace=True)
df.company.replace("SpaBo om","SpaBoom",inplace=True)
df.company.replace("Sparkplay Media","Sparkplay Media",inplace=True)
df.company.replace("Speci ficmedia","SpecificMedia",inplace=True)
df.company.replace("Specificmedia","SpecificMedia",inplace=True)
df.company.replace("SpendV iew","SpendView",inplace=True)
df.company.replace("Sphere","Sphere",inplace=True)
df.company.replace("Spiceworks","Spiceworks",inplace=True)
df.company.replace("Spire","Spire",inplace=True)
df.company.replace("Spock","Spock",inplace=True)
df.company.replace("Spoke","Spoke",inplace=True)
df.company.replace("Spot  Runner","Spot Runner",inplace=True)
df.company.replace("Spot R unner","Spot Runner",inplace=True)
df.company.replace("Spot Runner","Spot Runner",inplace=True)
df.company.replace("Spotplex","Spotplex",inplace=True)
df.company.replace("SquareTrade","SquareTrade",inplace=True)
df.company.replace("St rands","Strands",inplace=True)
df.company.replace("StartForce","Startforce",inplace=True)
df.company.replace("Strand s","Strands",inplace=True)
df.company.replace("Strands","Strands",inplace=True)
df.company.replace("StumbleUpon","StumbleUpon",inplace=True)
df.company.replace("Styky","Styky",inplace=True)
df.company.replace("Su rf Canyon","Surf Canyon",inplace=True)
df.company.replace("Suga rCRM","SugarCRM",inplace=True)
df.company.replace("Sugar Inc","Sugar Inc",inplace=True)
df.company.replace("SugarCR M","SugarCRM",inplace=True)
df.company.replace("SugarCRM ","SugarCRM",inplace=True)
df.company.replace("Supp lyFrame","SupplyFrame",inplace=True)
df.company.replace("Suppor t Space","Support Space",inplace=True)
df.company.replace("Sur f Canyon","Surf Canyon",inplace=True)
df.company.replace("Sw ivel","Swivel",inplace=True)
df.company.replace("SwapDrive","SwapDrive",inplace=True)
df.company.replace("Switch2Health","Switch2Health",inplace=True)
df.company.replace("Swivel","Swivel",inplace=True)
df.company.replace("Syla ntro","Sylantro",inplace=True)
df.company.replace("Sylantro","Sylantro",inplace=True)
df.company.replace("Sylantro ","Sylantro",inplace=True)
df.company.replace("Symplified","Symplified",inplace=True)
df.company.replace("Synthasite","Synthasite",inplace=True)
df.company.replace("Ta gged","Tagged",inplace=True)
df.company.replace("Tagge d","Tagged",inplace=True)
df.company.replace("Tagged","Tagged",inplace=True)
df.company.replace("Tagworld","TagWorld",inplace=True)
df.company.replace("Talk Plus","TalkPlus",inplace=True)
df.company.replace("Taltopia","Taltopia",inplace=True)
df.company.replace("Tangler","Tangler",inplace=True)
df.company.replace("Tapulous","Tapulous",inplace=True)
df.company.replace("Tar getSpot","TargetSpot",inplace=True)
df.company.replace("Tastemakers","Tastemakers",inplace=True)
df.company.replace("Te achStreet","Teachstreet",inplace=True)
df.company.replace("Te chnorati","Technorati",inplace=True)
df.company.replace("Te neros","Teneros",inplace=True)
df.company.replace("Tea ch The People","Teach The People",inplace=True)
df.company.replace("TeamStreamz","TeamStreamz",inplace=True)
df.company.replace("Techn orati","Technorati",inplace=True)
df.company.replace("Technorati","Technorati",inplace=True)
df.company.replace("TeleFlip","Teleflip",inplace=True)
df.company.replace("Ten eros","Teneros",inplace=True)
df.company.replace("Teneros","Teneros",inplace=True)
df.company.replace("Terabitz","Terabitz",inplace=True)
df.company.replace("Tes la Motors","Tesla Motors",inplace=True)
df.company.replace("Tesla  Motors","Tesla Motors",inplace=True)
df.company.replace("Tesla Motors","Tesla Motors",inplace=True)
df.company.replace("Th oof","Thoof",inplace=True)
df.company.replace("The Auteurs","The Auteurs",inplace=True)
df.company.replace("The Feedroom","The FeedRoom",inplace=True)
df.company.replace("The Find","TheFind",inplace=True)
df.company.replace("The Poin t","The Point",inplace=True)
df.company.replace("The Point","The Point",inplace=True)
df.company.replace("TheFin d","TheFind",inplace=True)
df.company.replace("TheFind","TheFind",inplace=True)
df.company.replace("TheLadde rs","TheLadders",inplace=True)
df.company.replace("ThisNext","ThisNext",inplace=True)
df.company.replace("Three Rings","Three Rings",inplace=True)
df.company.replace("Thumbpla y","Thumbplay",inplace=True)
df.company.replace("Ticke tsNow","TicketsNow",inplace=True)
df.company.replace("TicketLe ap","TicketLeap",inplace=True)
df.company.replace("Tiny  Pictures","Tiny Pictures",inplace=True)
df.company.replace("Tiny Pictures","Tiny Pictures",inplace=True)
df.company.replace("Tizra","Tizra",inplace=True)
df.company.replace("Tokbo x","TokBox",inplace=True)
df.company.replace("Tokbox","TokBox",inplace=True)
df.company.replace("Topix","Topix",inplace=True)
df.company.replace("TotalT akeout","TotalTakeout",inplace=True)
df.company.replace("Tour nEase","TournEase",inplace=True)
df.company.replace("TournEase","TournEase",inplace=True)
df.company.replace("Tr iggit","Triggit",inplace=True)
df.company.replace("Trave lMuse","TravelMuse",inplace=True)
df.company.replace("Treemo","Treemo",inplace=True)
df.company.replace("Tremor  Media","Tremor Media",inplace=True)
df.company.replace("Tremor Media","Tremor Media",inplace=True)
df.company.replace("TrialPay ","TrialPay",inplace=True)
df.company.replace("TripIt","TripIt",inplace=True)
df.company.replace("Tripolo gy","Tripology",inplace=True)
df.company.replace("Tru stedID","TrustedID",inplace=True)
df.company.replace("Trul ia","Trulia",inplace=True)
df.company.replace("Trulia","Trulia",inplace=True)
df.company.replace("Trunkt","Trunkt",inplace=True)
df.company.replace("Truser a","Trusera",inplace=True)
df.company.replace("TrustedID","TrustedID",inplace=True)
df.company.replace("Tu tor","Tutor",inplace=True)
df.company.replace("Tumblr","Tumblr",inplace=True)
df.company.replace("Tur nHere","TurnHere",inplace=True)
df.company.replace("Turbine","Turbine",inplace=True)
df.company.replace("TurnHere","TurnHere",inplace=True)
df.company.replace("Twit ter","Twitter",inplace=True)
df.company.replace("Twitter","Twitter",inplace=True)
df.company.replace("TwoFish","Twofish",inplace=True)
df.company.replace("UGOBE","UGOBE",inplace=True)
df.company.replace("Underto ne Networks","Undertone Networks",inplace=True)
df.company.replace("Unis fair","Unisfair",inplace=True)
df.company.replace("UpDown","UpDown",inplace=True)
df.company.replace("UpTake","UpTake",inplace=True)
df.company.replace("Urban Mapping","Urban Mapping",inplace=True)
df.company.replace("Ustream","Ustream",inplace=True)
df.company.replace("Utt erz","Utterz",inplace=True)
df.company.replace("V-Enable","V-Enable",inplace=True)
df.company.replace("V-Enable ","V-Enable",inplace=True)
df.company.replace("VISUA LPLANT","VISUALPLANT",inplace=True)
df.company.replace("VM IX Media","VMIX Media",inplace=True)
df.company.replace("VMI X Media","VMIX Media",inplace=True)
df.company.replace("VMware","Vmware",inplace=True)
df.company.replace("Vantage Media","Vantage media",inplace=True)
df.company.replace("VentureBeat","VentureBeat",inplace=True)
df.company.replace("Veo h","Veoh",inplace=True)
df.company.replace("Veodia","Veodia",inplace=True)
df.company.replace("Veoh","Veoh",inplace=True)
df.company.replace("Veotag","Veotag",inplace=True)
df.company.replace("Verim atrix","Verimatrix",inplace=True)
df.company.replace("Verimatrix","Verimatrix",inplace=True)
df.company.replace("Vidshadow","Vidshadow",inplace=True)
df.company.replace("View points","Viewpoints",inplace=True)
df.company.replace("Vin dicia","Vindicia",inplace=True)
df.company.replace("VirtualLogix","VirtualLogix",inplace=True)
df.company.replace("Visibl e Path","Visible Path",inplace=True)
df.company.replace("Visible  Measures","Visible Measures",inplace=True)
df.company.replace("Visible Measures","Visible Measures",inplace=True)
df.company.replace("Visible Path","Visible Path",inplace=True)
df.company.replace("Visible Technologies","Visible Technologies",inplace=True)
df.company.replace("Visible World","VisibleWorld",inplace=True)
df.company.replace("VisualCV","VisualCV",inplace=True)
df.company.replace("Vitrue","Vitrue",inplace=True)
df.company.replace("Vivaty","Vivaty",inplace=True)
df.company.replace("Vivâ€ ™simo","Vivâ€™simo",inplace=True)
df.company.replace("Vivâ€™s imo","Vivâ€™simo",inplace=True)
df.company.replace("Vivâ€™si mo","Vivâ€™simo",inplace=True)
df.company.replace("Vivâ€™simo","Vivâ€™simo",inplace=True)
df.company.replace("Vizu","Vizu",inplace=True)
df.company.replace("Vlingo","Vlingo",inplace=True)
df.company.replace("Vol taix","Voltaix",inplace=True)
df.company.replace("Votigo","Votigo",inplace=True)
df.company.replace("Vtap","Vtap",inplace=True)
df.company.replace("Vudu","Vudu",inplace=True)
df.company.replace("Vuze","Vuze",inplace=True)
df.company.replace("Wate rfront Media","Waterfront Media",inplace=True)
df.company.replace("Water front Media","Waterfront Media",inplace=True)
df.company.replace("Waterfro nt Media","Waterfront Media",inplace=True)
df.company.replace("Waterfront Media","Waterfront Media",inplace=True)
df.company.replace("Wavemaker Software","Wavemaker Software",inplace=True)
df.company.replace("We sabe","Wesabe",inplace=True)
df.company.replace("WeShow","WeShow",inplace=True)
df.company.replace("Weathe rBill","WeatherBill",inplace=True)
df.company.replace("WebMynd","WebMynd",inplace=True)
df.company.replace("Webaroo","Webaroo",inplace=True)
df.company.replace("Weeb ly","Weebly",inplace=True)
df.company.replace("Wesabe","Wesabe",inplace=True)
df.company.replace("Wet paint","Wetpaint",inplace=True)
df.company.replace("Wetp aint","Wetpaint",inplace=True)
df.company.replace("Wetpai nt","Wetpaint",inplace=True)
df.company.replace("What They Like","What They Like",inplace=True)
df.company.replace("Whi tePages.com","WhitePages.com",inplace=True)
df.company.replace("Wi kia","Wikia",inplace=True)
df.company.replace("Widgetbo x","WidgetBox",inplace=True)
df.company.replace("Wikia ","Wikia",inplace=True)
df.company.replace("Wikimedia Foundation","Wikimedia Foundation",inplace=True)
df.company.replace("Wink","Wink",inplace=True)
df.company.replace("Wishpot","Wishpot",inplace=True)
df.company.replace("Wize","Wize",inplace=True)
df.company.replace("Woot","Woot",inplace=True)
df.company.replace("WorkL ight","Worklight",inplace=True)
df.company.replace("WorkLigh t","Worklight",inplace=True)
df.company.replace("World Vital Records","World Vital Records",inplace=True)
df.company.replace("WrapMail","WRAPmail",inplace=True)
df.company.replace("XAware","XAware",inplace=True)
df.company.replace("Xo opit","Xoopit",inplace=True)
df.company.replace("Xobni","Xobni",inplace=True)
df.company.replace("Xoopit","Xoopit",inplace=True)
df.company.replace("Xora","Xora",inplace=True)
df.company.replace("XunLight","XunLight",inplace=True)
df.company.replace("Yap","Yap",inplace=True)
df.company.replace("Yapta","Yapta",inplace=True)
df.company.replace("Yelp","Yelp",inplace=True)
df.company.replace("Yiel dBuild","YieldBuild",inplace=True)
df.company.replace("Yield  Software","Yield Software",inplace=True)
df.company.replace("Yo uSendIt","YouSendIt",inplace=True)
df.company.replace("Yod lee","Yodlee",inplace=True)
df.company.replace("Yodio","Yodio",inplace=True)
df.company.replace("YooNew","Yoonew",inplace=True)
df.company.replace("YouCastr","YouCastr",inplace=True)
df.company.replace("YouSe ndIt","YouSendIt",inplace=True)
df.company.replace("YouSendIt","YouSendIt",inplace=True)
df.company.replace("YouTube","YouTube",inplace=True)
df.company.replace("Your  Survival","Your Survival",inplace=True)
df.company.replace("Your Street","YourStreet",inplace=True)
df.company.replace("YourTru manShow","yourtrumanshow",inplace=True)
df.company.replace("YuMe","YuMe",inplace=True)
df.company.replace("Zan nel","Zannel",inplace=True)
df.company.replace("Zango","Zango",inplace=True)
df.company.replace("Zat too","Zattoo",inplace=True)
df.company.replace("Zazzle","Zazzle",inplace=True)
df.company.replace("Zecter","Zecter",inplace=True)
df.company.replace("Zeer","Zeer",inplace=True)
df.company.replace("Zen d Technologies","Zend Technologies",inplace=True)
df.company.replace("Zen iMax","ZeniMax",inplace=True)
df.company.replace("Zend Technologies","Zend Technologies",inplace=True)
df.company.replace("ZeniMax","ZeniMax",inplace=True)
df.company.replace("Zigabid","Zigabid",inplace=True)
df.company.replace("Zigabid ","Zigabid",inplace=True)
df.company.replace("Zill ow","Zillow",inplace=True)
df.company.replace("Zillow","Zillow",inplace=True)
df.company.replace("Zimbra","Zimbra",inplace=True)
df.company.replace("Zing","Zing",inplace=True)
df.company.replace("Zinio","Zinio",inplace=True)
df.company.replace("Zivity","Zivity",inplace=True)
df.company.replace("Zoji","Zoji",inplace=True)
df.company.replace("ZoomInfo","ZoomInfo",inplace=True)
df.company.replace("Zooo mr","Zooomr",inplace=True)
df.company.replace("Zuora","Zuora",inplace=True)
df.company.replace("Zv ents","Zvents",inplace=True)
df.company.replace("Zvents","Zvents",inplace=True)
df.company.replace("Zynga","Zynga",inplace=True)
df.company.replace("app2you","App2you",inplace=True)
df.company.replace("beRecr uited","beRecruited",inplace=True)
df.company.replace("bluepulse","bluepulse",inplace=True)
df.company.replace("comScore","comScore",inplace=True)
df.company.replace("comScore ","comScore",inplace=True)
df.company.replace("coolearth","Cool Earth",inplace=True)
df.company.replace("crowdSPRING","Crowdspring",inplace=True)
df.company.replace("de ca.tv","deca.tv",inplace=True)
df.company.replace("deviantART","DeviantArt",inplace=True)
df.company.replace("divorce 360","divorce360",inplace=True)
df.company.replace("dr op.io","Drop.io",inplace=True)
df.company.replace("drop.io","Drop.io",inplace=True)
df.company.replace("eEye","eEye",inplace=True)
df.company.replace("eH armony","eHarmony",inplace=True)
df.company.replace("eHa rmony","eHarmony",inplace=True)
df.company.replace("eJamming ","eJamming",inplace=True)
df.company.replace("eSo lar","eSolar",inplace=True)
df.company.replace("eSolar ","eSolar",inplace=True)
df.company.replace("eXelate","eXelate",inplace=True)
df.company.replace("eXp resso","Expresso",inplace=True)
df.company.replace("eduFire ","eduFire",inplace=True)
df.company.replace("fabr ik","Fabrik",inplace=True)
df.company.replace("fabrik","Fabrik",inplace=True)
df.company.replace("fabrik ","Fabrik",inplace=True)
df.company.replace("fatd oor","fatdoor",inplace=True)
df.company.replace("fatdoor","fatdoor",inplace=True)
df.company.replace("ffwd","FFWD",inplace=True)
df.company.replace("flur ry","Flurry",inplace=True)
df.company.replace("freeb ase","Freebase",inplace=True)
df.company.replace("freebase","Freebase",inplace=True)
df.company.replace("gAuto","gAuto",inplace=True)
df.company.replace("hi5","Hi5",inplace=True)
df.company.replace("hi5 ","Hi5",inplace=True)
df.company.replace("hubbuzz","hubbuzz",inplace=True)
df.company.replace("hulu","Hulu",inplace=True)
df.company.replace("iBiz  Software","iBiz Software",inplace=True)
df.company.replace("iControl","iControl",inplace=True)
df.company.replace("iLike","iLike",inplace=True)
df.company.replace("iPling :))","iPling",inplace=True)
df.company.replace("iRise","iRise",inplace=True)
df.company.replace("iSkoo t","iSkoot",inplace=True)
df.company.replace("iSkoot","iSkoot",inplace=True)
df.company.replace("im ageshack","Imageshack",inplace=True)
df.company.replace("introNetworks","introNetworks",inplace=True)
df.company.replace("iovation","iovation",inplace=True)
df.company.replace("kwir y","kwiry",inplace=True)
df.company.replace("litescape","Litescape",inplace=True)
df.company.replace("mB lox","Mblox",inplace=True)
df.company.replace("mBlox","Mblox",inplace=True)
df.company.replace("mEgo","mEgo",inplace=True)
df.company.replace("mTraks","mTraks",inplace=True)
df.company.replace("madKast","madKast",inplace=True)
df.company.replace("madKast ","madKast",inplace=True)
df.company.replace("mediaFO RGE","MediaFORGE",inplace=True)
df.company.replace("mpire","Mpire",inplace=True)
df.company.replace("mywaves","mywaves",inplace=True)
df.company.replace("neoSa ej","neoSaej",inplace=True)
df.company.replace("nex tbio","Nextbio",inplace=True)
df.company.replace("oDe sk","oDesk",inplace=True)
df.company.replace("oDesk","oDesk",inplace=True)
df.company.replace("oDesk ","oDesk",inplace=True)
df.company.replace("obo pay","Obopay",inplace=True)
df.company.replace("obop ay","Obopay",inplace=True)
df.company.replace("obopa y","Obopay",inplace=True)
df.company.replace("obopay","Obopay",inplace=True)
df.company.replace("ooma","Ooma",inplace=True)
df.company.replace("ooma ","Ooma",inplace=True)
df.company.replace("pbwiki","PBWiki",inplace=True)
df.company.replace("rPath","rPath",inplace=True)
df.company.replace("rV ita","rVita",inplace=True)
df.company.replace("richrelevance","Richrelevance",inplace=True)
df.company.replace("samfind","Samfind",inplace=True)
df.company.replace("seesm ic","Seesmic",inplace=True)
df.company.replace("seesmic","Seesmic",inplace=True)
df.company.replace("trueAnthem","Trueanthem",inplace=True)
df.company.replace("tubemo gul","TubeMogul",inplace=True)
df.company.replace("uTest","uTest",inplace=True)
df.company.replace("uber","uber",inplace=True)
df.company.replace("utoopia","utoopia",inplace=True)
df.company.replace("vbs tv","vbs tv",inplace=True)
df.company.replace("x+1","x+1",inplace=True)
df.company.replace("xkoto ","xkoto ",inplace=True)


##### Category Variable   (Noted blank values)

# Getting set of company names having category == "NA"
category_na_list = set(df.loc[df.category.isna(),"company"])

print("List of companies having NA/blank at category variable",category_na_list)

# Now i will check weather the company names mentioned in "category_na_list", have category values for other recodrs, If not, then 
# i have to google and find, then fill it.

df.loc[df.company.isin(category_na_list),"category"]   ### Have to google and find.

# {'Brilliant Telecom ',    --- telecom -- will code it as other
df.loc[df.company =="Brilliant Telecom ","category"]="other"

#  'CitizenHawk',           --- Use of brands online -- will code as web
df.loc[df.company =="CitizenHawk","category"]="web"

#  'Collective Intellect',  --- digital communications analytics platform  -- will code as consulting
df.loc[df.company =="Collective Intellect","category"]="consulting"

#  'Elastra Corporation',   --- develops software for designing, deploying, and managing application systems ---software
df.loc[df.company =="Elastra Corporation","category"]="software"

#  'Katalyst Media',        --- television series  --- will code as other
df.loc[df.company =="Katalyst Media","category"]="other"

#  'Minted',                --- Online marketplace company  --- will code as consulting
df.loc[df.company =="Minted","category"]="consulting"

#  'Nextbio',               --- software company ---software
df.loc[df.company =="Nextbio","category"]="software"

#  'Passenger',             --- helps companies engage with customers --  consulting
df.loc[df.company =="Passenger","category"]="consulting"

#  'Paxfire',               --- generates ad revenue for network operators  ---web
df.loc[df.company =="Paxfire","category"]="web"

#  'PluggedIn',             --- family entertainment website  ---web
df.loc[df.company =="PluggedIn","category"]="web"

#  'Sharpcast',             --- Computer program --- software
df.loc[df.company =="Sharpcast","category"]="software"

#  'Silicon Alley Insider',  --- This blog analyzes without any pretension the technology industry ---web
df.loc[df.company =="Silicon Alley Insider","category"]="web"

#  'SilkRoad Technology',    ---- human capital management software company  --- software
df.loc[df.company =="SilkRoad Technology","category"]="software"

#  'Vmware',                 ---- Computer software company --- software
df.loc[df.company =="Vmware","category"]="software"

#  'Webaroo',                ---- Software
df.loc[df.company =="Webaroo","category"]="software"

#  'Zend Technologies',      ---- Software 
df.loc[df.company =="Zend Technologies","category"]="software"

#  'eEye'}                   --- Software
df.loc[df.company =="eEye","category"]="software"

###############################################################################################################

#### City Variable.
## I treated missing value for "category" variable. Similarly we have to treat for "CITY" as well.
## Look for city name with in data set using company name, if not available, Google and find.

city_na_company_list=set(df.loc[df.city.isna(),"company"])
print(city_na_company_list)

## Checking city names with in the data set.
city_company_list = df.loc[df.company.isin(city_na_company_list),["company","city"]]
city_company_list.to_csv("city_com.csv")

## Got few city list, rest have to google.

df.loc[df.company =="LifeLock","city"]="Tempe"
df.loc[df.company =="ChosenList.com","city"]="Scottsdale"
df.loc[df.company =="Facebook","city"]="Palo Alto"
df.loc[df.company =="Geni","city"]="West Hollywood"
df.loc[df.company =="Slacker","city"]="San Diego"
df.loc[df.company =="Technorati","city"]="San Francisco"
df.loc[df.company =="Mahalo","city"]="Santa Monica"
df.loc[df.company =="Veoh","city"]="San Diego"
df.loc[df.company =="Jingle Networks","city"]="Menlo Park"
df.loc[df.company =="Prosper","city"]="San Francisco"
df.loc[df.company =="Jajah","city"]="Mountain View"
df.loc[df.company =="Ustream","city"]="Mountain View"
df.loc[df.company =="Aggregate Knowledge","city"]="San Mateo"
df.loc[df.company =="Critical Metrics","city"]="Seattle"
df.loc[df.company =="Wize","city"]="San Mateo"
df.loc[df.company =="SodaHead","city"]="El Segundo"
df.loc[df.company =="Sphere","city"]="San Francisco"
df.loc[df.company =="MeeVee","city"]="Burlingame"
df.loc[df.company =="PBWiki","city"]="San Mateo"
df.loc[df.company =="Confabb","city"]="Washington"
df.loc[df.company =="Eurekster","city"]="San Francisco"
df.loc[df.company =="VentureBeat","city"]="San Francisco"
df.loc[df.company =="Labmeeting","city"]="Los Angeles"
df.loc[df.company =="New Relic","city"]="San Francisco"
df.loc[df.company =="Dizzywood","city"]="San Francisco"
df.loc[df.company =="Mad Mimi","city"]="Brooklyn"
df.loc[df.company =="Mixx","city"]="Washington"
df.loc[df.company =="ShoutWire","city"]="Sandston"  ## From VA (Virginia)
df.loc[df.company =="Estately","city"]="Seattle"

#####################################################################

### fundedDate Variable
# format this column to date from excel(Before importing the data).
# No Missing Values.
# Exctract Month and Year.

df["year"]=pd.DatetimeIndex(df.fundedDate).year
df["month"]=pd.DatetimeIndex(df.fundedDate).month

# Drop fundedDate
df.drop(["fundedDate"],axis=1,inplace=True)  ### Year and Month will be sufficient to do analysis.

#######################################################################

#### raisedAmt and raisedCurrency
# For Doing analysis, we have to bring all the amount under one single currency. 
# Converting everything into USD.
# Three type of currency -- USD, EUR, CAD

# CAD to USD. 1 CAD=.77 USD  So multiply the amount by 0.77
df.loc[df.raisedCurrency == "CAD","raisedAmt"] = (df.loc[df.raisedCurrency == "CAD",["raisedAmt"]])*0.77

# # 1 Euro = 1.16 USD
df.loc[df.raisedCurrency == "EUR",["raisedAmt"]] = df.loc[df.raisedCurrency == "EUR",["raisedAmt"]]*1.16

# ## USD
# df.loc[df.raisedCurrency == "USD",["Fund_raised_USD"]] = df.loc[df.raisedCurrency == "USD",["raisedAmt"]]

# Now Drop Variable raisedCurrency from data set.
# df.drop(["raisedAmt"],axis=1,inplace=True)
df.drop(["raisedCurrency"],axis=1,inplace=True)

df.to_csv("final.csv",index=False)
